# Generated by Django 3.1.2 on 2021-04-26 07:42

import blog.utilites
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_story', models.TextField(max_length=50, unique=True, verbose_name='Название')),
                ('text_small', models.TextField(blank=True, max_length=1000, verbose_name='Предпросмотр')),
                ('text_file', models.FileField(upload_to=blog.utilites.get_timestamp_path, verbose_name='Рассказ')),
                ('image_story', models.ImageField(blank=True, upload_to=blog.utilites.get_timestamp_path, verbose_name='Обложка')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рассказа')),
            ],
            options={
                'verbose_name': 'Рассказ',
                'verbose_name_plural': 'Рассказы',
            },
        ),
    ]
