# Generated by Django 3.1.2 on 2020-10-22 08:02

import blog.utilites
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_story',
            field=models.ImageField(blank=True, upload_to=blog.utilites.get_timestamp_path, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='story',
            name='text_file',
            field=models.FileField(blank=True, upload_to=blog.utilites.get_timestamp_path, verbose_name='Рассказ'),
        ),
        migrations.AddField(
            model_name='story',
            name='title_story',
            field=models.TextField(blank=True, max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='story',
            name='stories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рассказа'),
        ),
        migrations.AlterField(
            model_name='story',
            name='text_small',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Предпросмотр'),
        ),
    ]
